#!/usr/bin/env python3
"""
Additional rewrites for remaining filler articles
"""

rewrites_part2 = {
    'toxic-epidermal-necrolysis-life-threatening-drug-allergy': {
        'title': 'Toxic Epidermal Necrolysis: Drug-Induced Epidermal Detachment and Critical Management',
        'meta_description': 'TEN is a rare, severe drug reaction with 1-2 cases per million annually, presenting with widespread epidermal necrosis and mortality exceeding 25% despite aggressive intervention.',
        'tags': ['TEN', 'toxic epidermal necrolysis', 'severe cutaneous adverse reaction', 'drug allergy', 'medical emergency', 'epidermal necrosis'],
        'content': '''<h2>Clinical Overview</h2>
<p>Toxic Epidermal Necrolysis (TEN) represents the most severe form of drug-induced cutaneous adverse reaction, characterized by widespread epidermal necrosis and detachment affecting greater than 30% of body surface area, with mortality rates exceeding 25-30% despite optimal management. TEN exists on a spectrum of severe cutaneous adverse reactions (SCARs) that includes Stevens-Johnson Syndrome (SJS; <10% BSA), SJS/TEN overlap (10-30% BSA), and TEN (>30% BSA). The condition develops following exposure to specific medications, with onset typically 1-8 weeks after drug initiation. Once full-blown TEN develops with extensive epidermal necrosis, mortality risk becomes substantial due to complications including massive fluid and electrolyte losses, secondary bacterial infection with sepsis, respiratory compromise from airway mucosa involvement, and multi-organ failure. Early recognition and immediate management in specialized burn/critical care facilities are essential for survival.</p>

<h2>Epidemiology</h2>
<p>TEN occurs at an estimated incidence of 0.4-1.2 cases per million person-years in developed countries, making it a rare but clinically significant condition. Incidence varies geographically; some Asian populations (Thailand, China) show higher incidence rates (up to 5-8 per million person-years), with genetic predisposition and medication exposure patterns contributing to this variation. Peak age of onset is 50-60 years, though cases occur across all ages including children. Female predominance varies by study but approaches 1.5-2:1 in many cohorts. Medications account for approximately 80-90% of TEN cases; nonsteroidal anti-inflammatory drugs (NSAIDs), antibiotics (sulfonamides, beta-lactams), anticonvulsants (phenytoin, carbamazepine, phenobarbital), and acetaminophen are the most frequent culprits. Lamotrigine has emerged in recent decades as a leading cause of TEN in some populations. HIV-infected individuals show substantially increased TEN risk (100-1000-fold higher incidence); trimethoprim-sulfamethoxazole (TMP-SMX) is a particular risk in this population. Allopurinol carries one of the highest per-dose TEN risks among medications.</p>

<h2>Pathophysiology</h2>
<p>TEN involves massive CD8+ cytotoxic T lymphocyte-mediated epidermal keratinocyte death, resulting in separation at the dermal-epidermal junction. The mechanism initiates when drug metabolites (or in some cases unmetabolized drugs) act as haptens binding to epidermal proteins, or alternatively, through direct recognition of drug-altered peptide-MHC complexes on keratinocytes. Drug-specific CD8+ T cells recognize these altered antigens and release cytotoxic granules containing perforin and granzymes, which create pores in target cell membranes and trigger apoptosis cascades. Activated CD4+ T cells contribute through production of inflammatory cytokines (TNF-α, IL-2, IFN-γ). The massive scale of apoptosis (estimated 30-50% of all epidermal cells in TEN lesions) results from widespread drug metabolite distribution throughout the skin and systemic circulation. Genetic factors influence TEN susceptibility; HLA allele associations have been identified for specific drug-TEN combinations (HLA-B*1502 for carbamazepine in Asian populations, HLA-A*3101 for carbamazepine in European populations, HLA-B*5801 for allopurinol). These genetic associations suggest that certain HLA-peptide presentations efficiently present drug-derived antigens to T cells, dramatically increasing individual risk. Immune checkpoint dysregulation, with impaired regulatory T cell function, contributes to failure to terminate the cytotoxic response once initiated.</p>

<h2>Clinical Presentation</h2>
<p>TEN typically presents with a prodromal phase lasting 1-3 days characterized by fever (38.5-40°C), malaise, arthralgias, and pharyngitis—symptoms suggestive of viral illness. A mucopurulent exudate in the oral cavity is highly characteristic and occurs in >90% of cases. Cutaneous symptoms begin with burning pain and pruritus preceding visible lesions by 24-48 hours; patients often describe intense skin tenderness to touch. Widespread erythema appears, initially resembling morbilliform drug eruption with targetoid or atypical target lesions (irregular borders, large size, atypical color patterns). Unlike typical drug rashes, the erythema rapidly coalesces, and within 24-72 hours, epidermal detachment becomes evident—positive Nikolsky sign (gentle pressure or rubbing of skin causes full-thickness epidermal sloughing) is pathognomonic. Large areas of skin separate from dermis, leaving raw, weeping surfaces. Flaccid blisters form due to massive subepidermal fluid accumulation. By peak presentation, 30-95% of body surface area shows epidermal necrosis and detachment.</p>

<p>Mucosal involvement is near-universal; oral mucosa shows erosions, ulcerations, and pseudomembranous lesions covering 90-100% of oral surfaces in severe cases. Ocular involvement (in 50-80% of cases) presents with severe conjunctivitis, epithelial keratitis, adhesions (symblepharon formation), and in severe cases, corneal scarring and blindness. Genital and anal mucosal erosions occur in 25-40% of cases with significant morbidity. Pharyngeal and esophageal involvement causes dysphagia and risk of aspiration. Respiratory tract involvement (rare but critical) manifests as dyspnea, stridor, or hypoxemia from sloughing of tracheobronchial epithelium. Constitutional symptoms include high fever (38-40°C) refractory to antipyretics, tachycardia, hypotension, and signs of systemic inflammation. Fluid losses from massive surface area epidermal detachment can exceed those of thermal burns of comparable size, leading to profound hypovolemia, electrolyte derangements, and acute kidney injury if inadequately replaced.</p>

<h2>Diagnosis</h2>
<p>Diagnosis combines clinical presentation with histopathologic confirmation. Clinical criteria include: (1) onset typically 1-8 weeks after drug exposure (often a new medication); (2) positive Nikolsky sign with rapid epidermal detachment; (3) involvement of >30% BSA; (4) mucosal erosions in >2 sites; (5) fever and severe systemic symptoms. The diagnosis should be suspected in any patient with extensive epidermal detachment and recent medication exposure. Skin biopsy is essential for confirmation; specimens show full-thickness epidermal necrosis with separation at the dermal-epidermal junction, minimal or absent dermal inflammation (in contrast to SJS, which shows prominent dermal inflammation), and widespread apoptotic keratinocytes throughout the epidermis. Direct immunofluorescence is negative, helping exclude autoimmune blistering diseases. Electron microscopy, if available, demonstrates ultrastructural evidence of apoptosis with intact cell membranes and condensed nuclei. Laboratory findings include elevated white blood cell count (often 15,000-25,000/μL) with left shift and toxic changes, mild anemia from hemodilution, elevated liver enzymes, and elevated creatinine (pre-renal or intrinsic acute kidney injury).</p>

<p>The Severity of Illness Score for TEN (SJS/TEN-SOS) stratifies mortality risk based on clinical and laboratory parameters at presentation: age >40 years, heart rate >120, presence of infection/sepsis, bilirubin >1.4 mg/dL, glucose >252 mg/dL, and BUN >25 mg/dL. Cumulative scoring predicts mortality risk from approximately 3% (score 0-1) to >90% (score 6-7), allowing risk stratification and determination of management intensity. Additional assessment includes evaluation for infection through blood, urine, and wound cultures; identification of the offending medication through careful history and timeline analysis (dates of medication initiation correlated with symptom onset); and screening for HLA alleles associated with specific drugs if genetic data is available.</p>

<h2>Treatment</h2>
<p>Immediate discontinuation of all potentially culprit medications is paramount. Once TEN is suspected, the offending drug must be stopped immediately; the benefit of continued therapy does not outweigh the risk of TEN progression. Management of established TEN requires intensive multidisciplinary care comparable to severe burn management, ideally in specialized burn units or critical care facilities with experience in SCAR management. The following interventions are essential:</p>

<p><strong>Fluid Resuscitation:</strong> Massive fluid losses occur from denuded skin; IV fluids calculated using modified Parkland formula (3-4 mL × %BSA denuded × body weight in kg per 24 hours, divided among remaining fluid spaces) maintain hemodynamic stability and urine output of 0.5-1 mL/kg/hour. Crystalloid-based resuscitation (normal saline or Lactated Ringer's) is preferred; colloids provide limited benefit and carry increased thrombotic risk. Electrolyte monitoring every 2-4 hours with correction of hypokalemia, hyponatremia, and acid-base disturbances is essential.</p>

<p><strong>Systemic Corticosteroids:</strong> High-dose corticosteroid therapy (methylprednisolone 1-1.5 g IV daily for 3-5 days, followed by oral prednisone 1-1.5 mg/kg/day with gradual taper over 3-6 weeks) remains the most widely used immunosuppressive approach, despite limited controlled trial evidence. Some retrospective data suggest improved outcomes and decreased mortality when high-dose corticosteroids are initiated within 3-5 days of symptom onset, though initiating therapy after day 10 shows diminishing benefit. Corticosteroids suppress the cytotoxic T cell response, reducing ongoing keratinocyte death.</p>

<p><strong>Intravenous Immunoglobulin (IVIG):</strong> Multiple reports and retrospective cohort analyses suggest IVIG (2 g/kg total dose administered over 3-5 days) may benefit TEN patients, particularly when initiated early. Proposed mechanism includes blocking Fas-FasL interactions (which mediate apoptosis in TEN) through competition for ligand binding, though controlled trials demonstrating efficacy remain limited. Some centers use IVIG as first-line therapy or in combination with corticosteroids.</p>

<p><strong>TNF-α Inhibitors:</strong> Infliximab (anti-TNF-α monoclonal antibody) has been studied as adjunctive therapy; some case series report improved outcomes with early infliximab administration (5 mg/kg IV infusion), though controlled trial evidence is lacking. TNF-α likely contributes to the systemic inflammatory cascade in TEN.</p>

<p><strong>Cyclosporine:</strong> Cyclosporine (3-5 mg/kg/day) has been used in some centers as an alternative to or in combination with corticosteroids for steroid-refractory cases or as first-line therapy in some institutions, with variable reported outcomes. The immunosuppressive mechanism differs from corticosteroids, making combination therapy potentially synergistic.</p>

<p><strong>Wound Care:</strong> Meticulous skin care with non-adherent dressings (silicone-based, silver sulfadiazine-treated gauze, or specialized burn dressings) prevents infection and promotes re-epithelialization. Debridement of necrotic tissue minimizes infection risk. Temperature control through warm ambient environment (28-32°C) prevents hypothermia-induced complications.</p>

<p><strong>Infection Prevention and Monitoring:</strong> Aggressive infection screening with frequent blood, urine, and wound cultures; prophylactic antibiotic protocols may be employed in specialized burn centers. However, empiric broad-spectrum antibiotics are deferred unless culture evidence of infection exists, to minimize antibiotic-associated complications. Careful monitoring for sepsis (fever, hypotension, tachycardia, organ dysfunction) with rapid escalation of antibiotics if infection develops.</p>

<p><strong>Supportive Care:</strong> Nutritional support with high-protein enteral feeding (by nasogastric tube if oral intake limited) supports healing and immune function. Pain management with opioids (morphine, hydromorphone) controls severe pain from denuded skin. Airway management with intubation if upper airway involvement threatens; tracheostomy may be necessary for prolonged intubation. Ocular care with frequent irrigation, topical antibiotics, and ophthalmology consultation to minimize scarring.</p>

<h2>Prognosis</h2>
<p>Mortality rates vary based on extent of disease and timing of recognition/treatment. Overall mortality ranges from 25-35% despite optimal therapy. Prognostic factors include: age >40 years (dramatically increases mortality), BSA involvement >50%, presence of infection/sepsis, and elevated SJS/TEN-SOS score. Early recognition and initiation of therapy within 1-3 days of symptom onset significantly improves survival compared to delayed diagnosis. Long-term morbidity is substantial in survivors; ocular sequelae include scarring, dry eye, and vision impairment in 30-50% of survivors. Cutaneous scarring is rare but can occur. Psychosocial sequelae from trauma and prolonged hospitalization are significant.</p>

<h2>When to See a Dermatologist</h2>
<p>Any suspicion of severe drug reaction warrants immediate dermatology consultation and urgent transfer to specialized centers experienced in SCAR management. The distinction between less severe drug reactions and TEN must be established rapidly, as TEN requires emergency-level intervention.</p>

<h2>FAQ</h2>
<h3>Is TEN always caused by medications?</h3>
<p>Approximately 80-90% of TEN cases are medication-induced. Rare cases (10-20%) are associated with infections (particularly mycoplasma pneumoniae in SJS, though less common in TEN), vaccination, or malignancy (lymphoma, other cancers can trigger SJS/TEN-like eruptions through paraneoplastic mechanisms). However, the most common scenario is medication exposure 1-8 weeks prior to symptom onset. In cases where no clear medication is identified, careful history review often reveals over-the-counter medications, herbal supplements, or medications taken intermittently that patients may not initially report.</p>

<h3>Can someone survive TEN if they reach a hospital quickly?</h3>
<p>Early presentation dramatically improves survival. Patients reaching specialized centers within 1-3 days of symptom onset show approximately 15-25% mortality compared to 35-50% mortality in cases diagnosed after a week of symptoms. However, even with optimal early care, mortality remains significant (15-25%) because the underlying immune-mediated process may continue despite immunosuppression. This emphasizes the importance of preventing TEN through genetic screening before high-risk medications (particularly carbamazepine in HLA-B*1502-positive individuals) are prescribed in high-risk populations.</p>

<h3>What happens to patients who survive TEN?</h3>
<p>Survivors face significant long-term morbidity. Ocular complications occur in 30-50% of survivors: scarring (symblepharon), dry eye disease, visual impairment, and corneal opacity. Aggressive ophthalmology management during acute phase (preventing adhesions, maintaining moisture) minimizes scarring risk. Cutaneous involvement is usually limited to post-inflammatory hyperpigmentation that gradually improves; true scarring is uncommon except in areas of secondary infection. Psychological sequelae are substantial; survivors frequently experience post-traumatic stress disorder, body image disturbance, and anxiety related to future medication use. Multidisciplinary rehabilitation and mental health support are essential for recovery.</p>

<h3>Are there genetic tests to prevent TEN?</h3>
<p>HLA genetic testing before high-risk medication use can identify individuals at dramatically elevated risk for drug-specific TEN and prevent the condition. Testing for HLA-B*1502 before carbamazepine use is recommended in Asian populations (where frequency of allele is 5-10% vs. <1% in Europeans), reducing TEN incidence from approximately 1 in 500 to 1 in 5,000 with carbamazepine avoidance in positive individuals. HLA-A*3101 testing for carbamazepine and some other anticonvulsants is increasingly recommended in European populations. Testing for allopurinol (HLA-B*5801) is increasingly recommended before initiation, particularly in Asian populations. However, a negative HLA test does not eliminate TEN risk entirely, as non-HLA mechanisms contribute, and testing is not yet standard of care for all medications. The cost-benefit analysis of HLA testing varies by population and medication.</p>

<h2>References</h2>
<div class="article-references" style="font-size:0.92em;line-height:1.7;color:#555;">
<ol>
<li>Roujeau JC, Stern RS. Severe adverse cutaneous reactions to drugs. N Engl J Med. 1994;331(19):1272-1285.</li>
<li>Revuz J, Penso D, Roujeau JC, et al. Toxic epidermal necrolysis. Clinical findings and prognostic factors in 87 patients. Arch Dermatol. 1987;123(9):1160-1165.</li>
<li>Sasseville D, Carr D. Systemic contact dermatitis and internal exposure to allergens. J Am Acad Dermatol. 1998;38(3):376-388.</li>
<li>Mockenhaupt M, Viboud C, Dunant A, et al. Stevens-Johnson syndrome and toxic epidermal necrolysis: assessment of medication causal relationships in a worldwide database. J Am Acad Dermatol. 2008;59(4):547-556.</li>
<li>Bastuji-Garin S, Fouchard N, Bertocchi M, et al. SCORTEN: a severity-of-illness score for toxic epidermal necrolysis. J Invest Dermatol. 2000;115(2):149-153.</li>
<li>Chung WH, Hung SI, Hong HS, et al. Medical genetics: a marker for Stevens-Johnson Syndrome. Nature. 2004;428(6982):486.</li>
<li>Sekula P, Dunant A, Mockenhaupt M, et al. Comprehensive survival analysis of a cohort of patients with Stevens-Johnson syndrome and toxic epidermal necrolysis managed at specialized centers. J Invest Dermatol. 2013;133(5):1197-1204.</li>
<li>Paquet P, Pierard GE. Erythema multiforme and related conditions. J Am Acad Dermatol. 2003;48(2):167-180.</li>
<li>Roujeau JC, Chosidow O, Saiag P, Roux JC, Briggs M. Toxic epidermal necrolysis (Lyell syndrome). J Am Acad Dermatol. 1990;23(6):1039-1058.</li>
<li>Harr T, French LE. Toxic epidermal necrolysis and Stevens-Johnson syndrome. Orphanet J Rare Dis. 2010;5:39.</li>
</ol>
</div>'''
    }
}

print("Part 2 rewrites prepared. Ready to integrate...")
